name: Sync to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to personal repo
        run: |
          git remote add personal https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/park3hho/MES_FE.git
          git push personal main --force